(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(Info-additional-directory-list (quote ("~/.emacs.d/info/")))
 '(TeX-PDF-mode t)
 '(TeX-master nil)
 '(TeX-output-view-style (quote (("^dvi$" ("^landscape$" "^pstricks$\\|^pst-\\|^psfrag$") "%(o?)dvips -t landscape %d -o && gv %f") ("^dvi$" "^pstricks$\\|^pst-\\|^psfrag$" "%(o?)dvips %d -o && gv %f") ("^dvi$" ("^a4\\(?:dutch\\|paper\\|wide\\)\\|sem-a4$" "^landscape$") "%(o?)xdvi %dS -paper a4r -s 0 %d") ("^dvi$" "^a4\\(?:dutch\\|paper\\|wide\\)\\|sem-a4$" "%(o?)xdvi %dS -paper a4 %d") ("^dvi$" ("^a5\\(?:comb\\|paper\\)$" "^landscape$") "%(o?)xdvi %dS -paper a5r -s 0 %d") ("^dvi$" "^a5\\(?:comb\\|paper\\)$" "%(o?)xdvi %dS -paper a5 %d") ("^dvi$" "^b5paper$" "%(o?)xdvi %dS -paper b5 %d") ("^dvi$" "^letterpaper$" "%(o?)xdvi %dS -paper us %d") ("^dvi$" "^legalpaper$" "%(o?)xdvi %dS -paper legal %d") ("^dvi$" "^executivepaper$" "%(o?)xdvi %dS -paper 7.25x10.5in %d") ("^dvi$" "." "%(o?)xdvi %dS %d") ("^pdf$" "." "evince %o") ("^html?$" "." "x-www-browser %o"))))
 '(ansi-color-for-comint-mode t)
 '(asm-comment-char 35)
 '(auto-compression-mode t)
 '(backup-by-copying t)
 '(backup-directory-alist (quote (("." . "~/.local/share/backup"))))
 '(before-save-hook (quote (time-stamp)))
 '(bookmark-default-file "~/.emacs.d/.emacs.bmk")
 '(c-default-style (quote ((java-mode . "java") (awk-mode . "awk") (other . "java"))))
 '(calendar-latitude 37.7)
 '(calendar-location-name "Cedar City, UT")
 '(calendar-longitude -113)
 '(calendar-mark-holidays-flag t)
 '(canlock-password "281b52b9f15f65f198b9980970974fb21faa4950")
 '(case-fold-search t)
 '(ccm-recenter-at-end-of-file t)
 '(column-number-mode t)
 '(completion-styles (quote (basic partial-completion emacs22 initials)))
 '(current-language-environment "UTF-8")
 '(default-abbrev-mode t t)
 '(default-input-method "TeX")
 '(delete-by-moving-to-trash t)
 '(delete-old-versions t)
 '(delete-selection-mode t)
 '(desktop-path (quote ("~/.emacs.d" "." "~")))
 '(desktop-save-mode t)
 '(diary-file "~/Documents/diary")
 '(dired-dwim-target t)
 '(dired-omit-files "^\\.?#\\|^\\..*")
 '(doc-view-resolution 120)
 '(erc-auto-query (quote window-noselect))
 '(erc-autoaway-mode t)
 '(erc-away-nickname "ian|away")
 '(erc-fill-mode nil)
 '(erc-fill-prefix "        ")
 '(erc-log-channels-directory "~/.emacs.d/log")
 '(erc-modules (quote (autoaway autojoin button completion irccontrols list log match menu move-to-prompt netsplit networks noncommands readonly ring scrolltobottom services stamp track)))
 '(erc-nick "iandalton")
 '(erc-nick-notify-timeout 5000)
 '(eshell-modules-list (quote (eshell-alias eshell-banner eshell-basic eshell-cmpl eshell-dirs eshell-glob eshell-hist eshell-ls eshell-pred eshell-prompt eshell-rebind eshell-script eshell-term eshell-unix)))
 '(fill-column 72)
 '(flyspell-abbrev-p t)
 '(font-use-system-font t)
 '(g-user-email "iain.dalton@gmail.com")
 '(global-font-lock-mode t)
 '(gnus-buttonized-mime-types (quote ("multipart/signed")))
 '(gnus-directory "~/.emacs.d/News/")
 '(gnus-summary-line-format "%U%R%z%(%[%4L %d %-23,23f │%) %B%*%s
")
 '(gnus-treat-display-smileys nil)
 '(history-delete-duplicates t)
 '(icomplete-mode t)
 '(ido-create-new-buffer (quote always))
 '(ido-decorations (quote ("
-> " "" "
   " "
   ..." "[" "]" " [No match]" " [Matched]" " [Not readable]" " [Too big]" " [Confirm]")))
 '(ido-enable-flex-matching t)
 '(ido-everywhere t)
 '(ido-mode (quote both) nil (ido))
 '(indent-tabs-mode nil)
 '(inferior-lisp-program "sbcl" t)
 '(inhibit-startup-screen t)
 '(ispell-local-dictionary "en-w_accents")
 '(ispell-personal-dictionary "~/Documents/food/recipes.aspell")
 '(ispell-program-name "aspell")
 '(js2-basic-offset 4)
 '(js2-bounce-indent-flag t)
 '(js2-enter-indents-newline t)
 '(js2-language-version 150)
 '(kept-new-versions 16)
 '(kept-old-versions 2)
 '(longlines-wrap-follows-window-size t)
 '(mail-source-directory "~/.emacs.d/gnus/Mail/")
 '(mail-user-agent (quote gnus-user-agent))
 '(message-directory "~/.emacs.d/Mail/")
 '(mouse-yank-at-point t)
 '(org-agenda-custom-commands (quote (("n" "Agenda and all TODO's" ((agenda "") (alltodo))) ("H" "School and Home Lists" ((agenda) (tags-todo "SCHOOL") (tags-todo "HOME") (tags-todo "ERRAND") (tags-todo "HW") (tags-todo "READING") (tags-todo "COMPUTER"))) ("D" "Daily Action List" ((agenda "" ((org-agenda-ndays 1) (org-agenda-sorting-strategy (quote ((agenda time-up priority-down tag-up)))) (org-deadline-warning-days 0))))) ("P" "Office and Home Lists" ((tags "PROJECT"))))))
 '(org-agenda-exporter-settings (quote ((ps-print-color-p (quote black-white)))))
 '(org-agenda-files (quote ("~/Documents/school/biol1610/biol1610-agenda.org" "~/Documents/school/biol1615/biol1615-agenda.org" "~/Documents/school/philosophy-club/philclub-agenda.org" "~/Documents/school/mlp-club/mlpclub-agenda.org" "~/Documents/gtd.org")))
 '(org-agenda-include-diary t)
 '(org-agenda-start-on-weekday nil)
 '(org-agenda-with-colors t)
 '(org-alphabetical-lists t)
 '(org-babel-load-languages (quote ((emacs-lisp . t) (dot . t) (ditaa . t))))
 '(org-capture-templates (quote (("t" "Todo" entry (file+headline "~/Documents/gtd.org" "Tasks") "* TODO %^{Brief Description} %^g
%?
Added: %U") ("w" "Waiting for" entry (file+headline "~/Documents/gtd.org" "Waiting for") "* WAITING %^{Brief Description} %^g
%?
Added: %U") ("s" "Someday" entry (file+headline "~/Documents/someday.org" "New Projects") "*** %^{Brief Description} :PROJECT:
%?
Added: %U") ("j" "Journal" entry (file+datetree "~/Documents/journal.org") "

* %U %^{Heading}

%?
"))))
 '(org-ditaa-jar-path /usr/share/ditaa/ditaa\.jar)
 '(org-refile-targets (quote (("~/Documents/gtd.org" :maxlevel . 1) ("~/Documents/someday.org" :maxlevel . 1) ("~/Documents/calibre-library.org" :maxlevel . 2))))
 '(org-tags-exclude-from-inheritance (quote ("PROJECT")))
 '(pcomplete-cycle-completions nil)
 '(rcirc-authinfo (quote (("freenode" nickserv "iandalton" "235689741a"))))
 '(rcirc-default-nick "iandalton")
 '(rcirc-fill-flag nil)
 '(rcirc-keywords (quote ("ian")))
 '(rcirc-log-directory "~/.local/share/rcirc-log")
 '(rcirc-log-filename-function (quote rcirc-generate-log-path))
 '(rcirc-log-flag t)
 '(rcirc-server-alist (quote (("irc.freenode.net" :port 7000 :encryption tls))))
 '(rcirc-time-format "%H:%M:%S ")
 '(rcirc-track-minor-mode t)
 '(read-file-name-completion-ignore-case t)
 '(read-mail-command (quote gnus))
 '(safe-local-variable-values (quote ((backup-inhibited . t) (Package . DTRACE) (outline-pattern . "
;;;;+"))))
 '(save-place t nil (saveplace))
 '(save-place-file "~/.emacs.d/places")
 '(savehist-mode t)
 '(scroll-preserve-screen-position 1)
 '(send-mail-function (quote smtpmail-send-it))
 '(show-paren-mode t)
 '(slime-repl-history-file "~/.emacs.d/slime-history.eld")
 '(slime-startup-animation nil)
 '(tab-always-indent (quote complete))
 '(tab-width 4)
 '(tool-bar-mode nil)
 '(uniquify-buffer-name-style (quote forward) nil (uniquify))
 '(user-full-name "Ian Dalton")
 '(user-mail-address "iain.dalton@gmail.com")
 '(version-control t)
 '(whitespace-style (quote (face tabs trailing lines-tail empty)) t)
 '(x-select-enable-clipboard t)
 '(x-stretch-cursor t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(gnus-button ((t (:foreground "blue" :underline t :weight normal))))
 '(org-formula ((t (:foreground "Firebrick" :family "monospace"))))
 '(org-table ((t (:inherit fixed-pitch :foreground "Blue1"))))
 '(variable-pitch ((t (:height 1.2 :family "Sans Serif")))))
